name: "Build & Release [Android, iOS]"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
        # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

        # Setup Flutter
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.27.x
      - run: flutter --version

        # Install Dependencies
      - name: Install Dependencies
        run: flutter pub get
        
       # Building APK
      - name: Build APK
        run: flutter build apk --release

        # Build IPA ( IOS Build )
      - name: Build IPA
        run: flutter build ipa --no-codesign

      - name: Compress Archives and IPAs
        run: |
          cd build
          tar -czf ios_build.tar.gz ios

        # Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Releases
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
            build/ios_build.tar.gz
        
        # Create Release
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk,build/app/outputs/bundle/release/app-release.aab,build/ios_build.tar.gz"
          tag: v${{ github.RUN_NUMBER }}
          token: ${{ secrets.TOKEN }}